name: Hello World
author: rwxproject
description: rwx
inputs:
  who-to-greet:
    description: "who to greet"
    required: true
    default: rwx
outputs:
  time:
    description: "greet time"
runs:
  using: docker
  image: "Dockerfile"
  # entrypoint: 
  args:
    - ${{ inputs.who-to-greet }}
  # env:
    